{
 "title": "FastAPI Observability",
 "tags": [
  "fastapi",
  "observability"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "Errors/sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(app_errors_total[5m]))"
    }
   ]
  },
  {
   "title": "Warnings/sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(app_warnings_total[5m]))"
    }
   ]
  },
  {
   "title": "Application logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"fastapi-app\"}"
    }
   ]
  }
 ]
}